### ISSUE TITLE
پیشنهاد برای لاگ

### ISSUE THREAD

**Issue by Sosha1996** [OSMIran/FaNumberFixer#2]
۱. کنار خروجی لاگ توی جدول شماره بیوفته. یعنی یه ستون اضافه بشه و سطر به سطرش عدد بخوره از ۱ تا هر چی که هست

۲. یه ستون اضافه بشه برای ویرایش از توی JOSM
دومی رو باید البته خودم روش کار کنم و کدش رو میدم بهت

**Comment by Sosha1996** [comment]
http://localhost:8111/load_object?new_layer=true&objects=
اگر نود باشه بعد از 
objects=
n w r 
میگیره که یعنی 
n=node, w=way, r=relation.

مثلا نود:
http://localhost:8111/load_object?new_layer=true&objects=n747363757

مثلا way:
http://localhost:8111/load_object?new_layer=true&objects=w123456789

مثلا relation:
مثلا way:
http://localhost:8111/load_object?new_layer=true&objects=r123456789

فکر نمیکنم پیاده سازیش زیاد سخت باشه.

منبع: https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands

**Comment by FTABoy** [comment]
اگر اوکیه و مشکلی نیست این ایشو رو ببندم

**Comment by Sosha1996** [comment]
https://github.com/OSMIran/FaNumberFixer/commit/2bbf6225dba269440700d28502c5cf17d4ecff88
https://github.com/OSMIran/FaNumberFixer/commit/ca32a0185756b7c9c016291e582d81245760e15f
https://github.com/OSMIran/FaNumberFixer/commit/122e50fd6c768c70cbdfcd87ccb2f16db4e5e5f6

ممنون.
