### ISSUE TITLE
تمیز کردن کد

### ISSUE THREAD

**Issue by Sosha1996** [OSMIran/FaNumberFixer#3]
https://github.com/OSMIran/FaNumberFixer/blob/bd1085d7b50f45818ecbf2c4482c4bb3d13c884f/FaNumberFixer.py#L125

به این خطوط کامنت شده که انگار کپی شده بالایین نیازه؟

**Comment by FTABoy** [comment]
اره نیازه.
اینایی که کامنت شده از خط ۱۲۵ تا ۱۵۷ برای اصلاح ریلیشن ها هستش که ما چون تصمیم گرفتیم به ریلیشن ها دست نزنیم کدش رو کامنت کردم که اجرا نشه. ولی پاکش نکردم داشته باشیمش اگه لازم شد...

**Comment by Sosha1996** [comment]
احسنت. خیلی هم عالی.
